### ISSUE TITLE
Tracking semantics that are using KBuild

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#369]
- [ ] blockchain-k-plugin
- [ ] K tutorial
- [ ] KEVM: https://github.com/runtimeverification/evm-semantics/pull/1603
- [ ] KAVM: https://github.com/runtimeverification/avm-semantics/pull/330
- [ ] KCC
- [ ] AlgoEVM
- [x] KMIR: https://github.com/runtimeverification/mir-semantics/
